PROGS_LONGTEST_OBJS := longtest.o
PROGS_LONGTEST_OBJS := $(PROGS_LONGTEST_OBJS:%=$(TDIR)/longtest/%)
ALL_OBJS += $(PROGS_LONGTEST_OBJS)

$(TDIR)/bin/longtest : $(TSTART) $(PROGS_LONGTEST_OBJS) $(TLIBC)

